/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ptithcm.pe.views;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author tezca
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainFrame() {
        initComponents();
        setSize(1000, 750);
        setDefaultCloseOperation(MainFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setExtendedState(MainFrame.NORMAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnAddExpenditure = new javax.swing.JButton();
        btnListExpenditure = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnAddReceipt = new javax.swing.JButton();
        btnListReceipt = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnCloseTab = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        panelHome = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        mniLogin = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniAddExpenditureType = new javax.swing.JMenuItem();
        mniListExpenditureType = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniAddExpenditure = new javax.swing.JMenuItem();
        mniListExpenditure = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniAddReceiptType = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý chi tiêu");

        jToolBar1.setRollover(true);

        btnAddExpenditure.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAddExpenditure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_addExp32.png"))); // NOI18N
        btnAddExpenditure.setText("Thêm chi tiêu mới");
        btnAddExpenditure.setFocusable(false);
        btnAddExpenditure.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddExpenditure.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExpenditureActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAddExpenditure);

        btnListExpenditure.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnListExpenditure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_payment32.png"))); // NOI18N
        btnListExpenditure.setText("Danh sách chi tiêu");
        btnListExpenditure.setFocusable(false);
        btnListExpenditure.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListExpenditure.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnListExpenditure);
        jToolBar1.add(jSeparator6);

        btnAddReceipt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAddReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_addRec32.png"))); // NOI18N
        btnAddReceipt.setText("Thêm thu nhập mới");
        btnAddReceipt.setFocusable(false);
        btnAddReceipt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddReceipt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAddReceipt);

        btnListReceipt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnListReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_receipt32.png"))); // NOI18N
        btnListReceipt.setText("Danh sách thu nhập");
        btnListReceipt.setFocusable(false);
        btnListReceipt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListReceipt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnListReceipt);
        jToolBar1.add(jSeparator7);

        btnCloseTab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCloseTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_close32.png"))); // NOI18N
        btnCloseTab.setText("Đóng cửa sổ");
        btnCloseTab.setFocusable(false);
        btnCloseTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCloseTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCloseTab);

        tabbedPane.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Home", panelHome);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(80, 30));

        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        mniLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mniLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_login20.png"))); // NOI18N
        mniLogin.setText("Login");
        menuFile.add(mniLogin);

        mniLogout.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mniLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_logout.png"))); // NOI18N
        mniLogout.setText("Logout");
        menuFile.add(mniLogout);
        menuFile.add(jSeparator5);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniExit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_exit20.png"))); // NOI18N
        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        menuFile.add(mniExit);

        jMenuBar1.add(menuFile);

        jMenu2.setText("Manager");
        jMenu2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        mniAddExpenditureType.setText("Thêm phân loại chi tiêu mới");
        mniAddExpenditureType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddExpenditureTypeActionPerformed(evt);
            }
        });
        jMenu2.add(mniAddExpenditureType);

        mniListExpenditureType.setText("Danh mục phân loại chi tiêu");
        jMenu2.add(mniListExpenditureType);
        jMenu2.add(jSeparator2);

        mniAddExpenditure.setText("Thêm chi tiêu mới");
        jMenu2.add(mniAddExpenditure);

        mniListExpenditure.setText("Danh sách chi tiêu");
        jMenu2.add(mniListExpenditure);
        jMenu2.add(jSeparator3);

        mniAddReceiptType.setText("Thêm phân loại thu nhập mới");
        jMenu2.add(mniAddReceiptType);

        jMenuItem7.setText("Danh mục phân loại thu nhập");
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator4);

        jMenuItem9.setText("Thêm thu nhập mới");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Danh sách thu nhập");
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenu3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jMenuItem1.setText("Content");
        jMenu3.add(jMenuItem1);
        jMenu3.add(jSeparator1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_aboutUs.png"))); // NOI18N
        jMenuItem2.setText("About Us");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExpenditureActionPerformed
            
    }//GEN-LAST:event_btnAddExpenditureActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // TODO add your handling code here:
        int confirmResult = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình không?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION);
        
        if (confirmResult == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniAddExpenditureTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddExpenditureTypeActionPerformed
        // TODO add your handling code here:
        tabbedPane.add(new LoginFrame());
    }//GEN-LAST:event_mniAddExpenditureTypeActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExpenditure;
    private javax.swing.JButton btnAddReceipt;
    private javax.swing.JButton btnCloseTab;
    private javax.swing.JButton btnListExpenditure;
    private javax.swing.JButton btnListReceipt;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem mniAddExpenditure;
    private javax.swing.JMenuItem mniAddExpenditureType;
    private javax.swing.JMenuItem mniAddReceiptType;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniListExpenditure;
    private javax.swing.JMenuItem mniListExpenditureType;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JPanel panelHome;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
