/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.pe.UI.Receipt;

import com.ptithcm.pe.UI.Receipt.AddNewRevenuesTypeRec;
import java.awt.Frame;
import javax.swing.SwingUtilities;

/**
 *
 * @author tezca
 */
public class ListRevenuesTypeRPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListExpenditurePanel
     */
    public ListRevenuesTypeRPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        txtGroup = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(com.ptithcm.pe.util.Constraints.TITLE_LIST_RECEIPT);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 65);
        add(jSeparator1);
        jSeparator1.setBounds(0, 64, 860, 3);
        add(jSeparator2);
        jSeparator2.setBounds(30, 330, 788, 3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Danh mục", "Số tiền", "Thời gian", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 788, 225);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Mã:");
        add(jLabel3);
        jLabel3.setBounds(30, 350, 100, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Ngày tháng:");
        add(jLabel4);
        jLabel4.setBounds(30, 470, 100, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Phân loại:");
        add(jLabel5);
        jLabel5.setBounds(30, 390, 100, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Số tiền:");
        add(jLabel6);
        jLabel6.setBounds(30, 430, 100, 30);

        jTextField1.setMinimumSize(new java.awt.Dimension(100, 30));
        add(jTextField1);
        jTextField1.setBounds(130, 470, 240, 30);

        txtCode.setMinimumSize(new java.awt.Dimension(100, 30));
        add(txtCode);
        txtCode.setBounds(130, 350, 240, 30);

        txtGroup.setMinimumSize(new java.awt.Dimension(100, 30));
        add(txtGroup);
        txtGroup.setBounds(130, 390, 240, 30);

        txtAmount.setMinimumSize(new java.awt.Dimension(100, 30));
        add(txtAmount);
        txtAmount.setBounds(130, 430, 240, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Ghi chú:");
        add(jLabel7);
        jLabel7.setBounds(30, 510, 100, 30);

        txtNote.setWrapStyleWord(true);
        txtNote.setLineWrap(true);
        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane2.setViewportView(txtNote);

        add(jScrollPane2);
        jScrollPane2.setBounds(130, 510, 240, 90);

        btnAdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_add32.png"))); // NOI18N
        btnAdd.setText("Thêm mới");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(540, 390, 129, 42);

        btnRefresh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon_refresh32.png"))); // NOI18N
        btnRefresh.setText("Làm mới");
        add(btnRefresh);
        btnRefresh.setBounds(540, 470, 130, 42);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AddNewRevenuesTypeRec addNewRevenuesTypeRec = new AddNewRevenuesTypeRec((Frame) SwingUtilities.getWindowAncestor(this), true);
        addNewRevenuesTypeRec.setSize(800,500);
        addNewRevenuesTypeRec.setLocationRelativeTo(null);
        addNewRevenuesTypeRec.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtGroup;
    private javax.swing.JTextArea txtNote;
    // End of variables declaration//GEN-END:variables
}
